export const ADD_ITEM_CART = 'ADD_ITEM_CART'
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY'
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART'
export const REMOVE_ALL_CART = 'REMOVE_ALL_CART'

export const ADD_ITEM_CHECKOUT = 'ADD_ITEM_CHECKOUT'
export const REMOVE_ITEM_CHECKOUT = 'REMOVE_ITEM_CHECKOUT'