export const GET_PRODUCT_BY_CATEGORY_START = 'GET_PRODUCT_BY_CATEGORY_START'
export const GET_PRODUCT_BY_CATEGORY_SUCCESS = 'GET_PRODUCT_BY_CATEGORY_SUCCESS'
export const GET_PRODUCT_BY_CATEGORY_FAILURE = 'GET_PRODUCT_BY_CATEGORY_FAILURE'

export const GET_ATTRIBUTE_BY_CATEGORY_START = 'GET_ATTRIBUTE_BY_CATEGORY_START'
export const GET_ATTRIBUTE_BY_CATEGORY_SUCCESS = 'GET_ATTRIBUTE_BY_CATEGORY_SUCCESS'
export const GET_ATTRIBUTE_BY_CATEGORY_FAILURE = 'GET_ATTRIBUTE_BY_CATEGORY_FAILURE'

export const GET_PRODUCT_WITH_FILTER_START = 'GET_PRODUCT_WITH_FILTER_START'
export const GET_PRODUCT_WITH_FILTER_SUCCESS = 'GET_PRODUCT_WITH_FILTER_SUCCESS'
export const GET_PRODUCT_WITH_FILTER_FAILURE = 'GET_PRODUCT_WITH_FILTER_FAILURE'

export const SEARCH_PRODUCTS_START = 'SEARCH_PRODUCTS_START'
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS'
export const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE'